/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

import MyLib.Agent;
import MyLib.Block;
import MyLib.Booking;
import MyLib.Customer;
import MyLib.Detached;
import MyLib.Property;
import MyLib.PropertyManager;
import MyLib.SemiDetached;
import MyLib.Session;
import MyLib.TownHouse;
import MyLib.UserManager;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * */
public class AgentDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AgentDashboard.class.getName());
    private UserManager userManager;
    private PropertyManager propertyManager;
    private Agent agent;
    private Property selectedProperty = null;
    private Booking selectedBooking = null;

//This is the missing textfield
    private javax.swing.JTextField minPriceField = new javax.swing.JTextField(7);
    private javax.swing.JTextField maxPriceField = new javax.swing.JTextField(7);
    private javax.swing.JTextField minSizeField = new javax.swing.JTextField(7);
    private javax.swing.JTextField maxSizeField = new javax.swing.JTextField(7);
    
    /**
     *
     */
    public AgentDashboard(UserManager userManager, PropertyManager propertyManager, Agent agent) {
        this.userManager = userManager;
        this.propertyManager = propertyManager;
        this.agent = agent;
        initComponents();
        
        // This is the bypass
        injectFilters();
        
        setLocationRelativeTo(null);
        setupTable();
        setupRequestTable();
        loadBookingsToTable();
        loadPropertiesToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigatorPanel = new javax.swing.JPanel();
        requestsButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        propertiesButton = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        PropertiesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertyTable = new javax.swing.JTable();
        RequestPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        removeReservationButton = new javax.swing.JButton();
        confirmBookingButton = new javax.swing.JButton();
        removeBookingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavigatorPanel.setLayout(null);

        requestsButton.setText("Requests");
        requestsButton.addActionListener(this::requestsButtonActionPerformed);
        NavigatorPanel.add(requestsButton);
        requestsButton.setBounds(30, 120, 170, 60);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);
        NavigatorPanel.add(logoutButton);
        logoutButton.setBounds(30, 680, 170, 60);

        propertiesButton.setText("Properties");
        propertiesButton.addActionListener(this::propertiesButtonActionPerformed);
        NavigatorPanel.add(propertiesButton);
        propertiesButton.setBounds(30, 40, 170, 60);

        Parent.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Properties");

        propertyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Property ID", "Block Number", "Property Number", "Status", "Owner", "Property Price", "Property Size", "Property Floors", "Property Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(propertyTable);

        javax.swing.GroupLayout PropertiesPanelLayout = new javax.swing.GroupLayout(PropertiesPanel);
        PropertiesPanel.setLayout(PropertiesPanelLayout);
        PropertiesPanelLayout.setHorizontalGroup(
            PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        PropertiesPanelLayout.setVerticalGroup(
            PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        Parent.add(PropertiesPanel, "PropertiesPanel");

        jLabel3.setText("Requests");

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Property ID", "Block Number", "Property Number", "Status", "Booked By", "Property Price", "Property Size", "Property Floors", "Property Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        removeReservationButton.setText("Remove Reservation");
        removeReservationButton.addActionListener(this::removeReservationButtonActionPerformed);

        confirmBookingButton.setText("Confirm Booking");
        confirmBookingButton.addActionListener(this::confirmBookingButtonActionPerformed);

        removeBookingButton.setText("Remove Booking");
        removeBookingButton.addActionListener(this::removeBookingButtonActionPerformed);

        javax.swing.GroupLayout RequestPanelLayout = new javax.swing.GroupLayout(RequestPanel);
        RequestPanel.setLayout(RequestPanelLayout);
        RequestPanelLayout.setHorizontalGroup(
            RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(removeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestPanelLayout.createSequentialGroup()
                    .addContainerGap(688, Short.MAX_VALUE)
                    .addComponent(confirmBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)))
            .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RequestPanelLayout.createSequentialGroup()
                    .addContainerGap(686, Short.MAX_VALUE)
                    .addComponent(removeBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        RequestPanelLayout.setVerticalGroup(
            RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RequestPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(RequestPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(removeReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RequestPanelLayout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(confirmBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(539, Short.MAX_VALUE)))
            .addGroup(RequestPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(RequestPanelLayout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(removeBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );

        Parent.add(RequestPanel, "RequestPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void requestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestsButtonActionPerformed
        // TODO add your handling code here:
       CardLayout cl = (CardLayout)(Parent.getLayout());
       cl.show(Parent, "RequestPanel");
       loadBookingsToTable();
    }//GEN-LAST:event_requestsButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Session.logout();
        
        new Authentication(userManager, propertyManager).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void propertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesButtonActionPerformed
        // TODO add your handling code here:
       CardLayout cl = (CardLayout)(Parent.getLayout());
       cl.show(Parent, "PropertiesPanel");
       loadPropertiesToTable();
    }//GEN-LAST:event_propertiesButtonActionPerformed

    private void removeReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeReservationButtonActionPerformed
        // TODO add your handling code here:
        Booking selectedBooking = getSelectedBooking();
        
        if(selectedBooking != null) {
            Property property = selectedBooking.getProperty();
            
            if("Reserved".equals(property.getStatus())) {
                property.updateStatus("For Sale");
                property.setReservation(null);
                propertyManager.removeBooking(selectedBooking);
                
                JOptionPane.showMessageDialog(this, "Reservation removed.");
            }
            else {
                JOptionPane.showMessageDialog(this, "Selected property is not reserved.");
            }
            
            loadBookingsToTable();
            selectedBooking = null;
        }
    }//GEN-LAST:event_removeReservationButtonActionPerformed

    private void confirmBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBookingButtonActionPerformed
        // TODO add your handling code here:
        Booking selectedBooking = getSelectedBooking();

        if (selectedBooking != null) {
            Property property = selectedBooking.getProperty();
            Customer customer = selectedBooking.getCustomer();
            
            property.updateStatus("Reserved");
            property.setReservation(customer);

            
            
            ArrayList<Booking> bookings = propertyManager.getBookingForAgent(agent);
            ArrayList<Booking> toRemove = new ArrayList<>();
            for (Booking b : bookings) {
                if (b.getProperty() == property && b.getCustomer() != customer) {
                    toRemove.add(b);
                }
            }
            for (Booking b : toRemove) {
                propertyManager.removeBooking(b);
            }

            JOptionPane.showMessageDialog(this, "Booking confirmed!");
            
            loadBookingsToTable();
            loadPropertiesToTable();
            selectedBooking = null;
        }
    }//GEN-LAST:event_confirmBookingButtonActionPerformed

    private void removeBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookingButtonActionPerformed
        // TODO add your handling code here:
        Booking selectedBooking = getSelectedBooking();
        
        if(selectedBooking != null) {
            propertyManager.removeBooking(selectedBooking);
            JOptionPane.showMessageDialog(this, "Booking removed.");

            loadBookingsToTable();
            selectedBooking = null;
        }
    }//GEN-LAST:event_removeBookingButtonActionPerformed

    //Ito yung manual injection ng filter bar natin, since it was missing from the GUI designer. This is a workaround to add it back in.
    // This is a workaround for the fact that the filter bar was not added in the GUI designer
    private void injectFilters() {
        PropertiesPanel.removeAll();
        PropertiesPanel.setLayout(new java.awt.BorderLayout(10, 10));
        PropertiesPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        javax.swing.JPanel topArea = new javax.swing.JPanel(new java.awt.BorderLayout());
        
        javax.swing.JLabel title = new javax.swing.JLabel("Properties");
        title.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 24));
        topArea.add(title, java.awt.BorderLayout.NORTH);

        javax.swing.JPanel filterBar = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        filterBar.add(new javax.swing.JLabel("Min Price:"));
        filterBar.add(minPriceField);
        filterBar.add(new javax.swing.JLabel("Max Price:"));
        filterBar.add(maxPriceField);
        filterBar.add(new javax.swing.JLabel("Min Size:"));
        filterBar.add(minSizeField);
        filterBar.add(new javax.swing.JLabel("Max Size:"));
        filterBar.add(maxSizeField);

        javax.swing.JButton filterBtn = new javax.swing.JButton("Filter");
        filterBtn.addActionListener(e -> loadPropertiesToTable());
        filterBar.add(filterBtn);

        topArea.add(filterBar, java.awt.BorderLayout.SOUTH);

        PropertiesPanel.add(topArea, java.awt.BorderLayout.NORTH);
        PropertiesPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER); 
        
        PropertiesPanel.revalidate();
        PropertiesPanel.repaint();
    }

    // ==========================================
    // ADDED: Input Parser 
    // ==========================================
    private Double parseDoubleOrNull(String text){
        if (text == null || text.isEmpty()) return null;
        if (!text.matches("\\d+(\\.\\d+)?")) return null;
        return Double.parseDouble(text);
    }
    
    private Booking getSelectedBooking() {
        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) return null;

        int propertyId = (int) requestTable.getValueAt(selectedRow, 0);
        String customerName = (String) requestTable.getValueAt(selectedRow, 4);

        for (Booking booking : propertyManager.getBookingForAgent(agent)) {
            if (booking.getProperty().getPropertyId() == propertyId &&
                booking.getCustomer().getUsername().equals(customerName)) {
                return booking;
            }
        }

        return null;
    }

    //fixed filter and loop logic as well
    private void loadPropertiesToTable() {
        DefaultTableModel model = (DefaultTableModel) propertyTable.getModel();
        model.setRowCount(0); // Clear existing rows
        
        // 1. Grab values from our newly injected text fields
        Double minPrice = parseDoubleOrNull(minPriceField.getText());
        Double maxPrice = parseDoubleOrNull(maxPriceField.getText());
        Double minSize = parseDoubleOrNull(minSizeField.getText());
        Double maxSize = parseDoubleOrNull(maxSizeField.getText());

        // 2. Call the leader's Manager method (Passing null for the block number right now)
        java.util.ArrayList<Property> filteredProperties = propertyManager.filterProperties(null, minPrice, maxPrice);
        
        if (filteredProperties != null) {
            for(Property property : filteredProperties) { 
                
                // 3. Local check for sizes
                if (minSize != null && property.getPropertySize() < minSize) continue;
                if (maxSize != null && property.getPropertySize() > maxSize) continue;

                // 4. Safely pull types and owners
                String type = property.getClass().getSimpleName();
                String ownerName = (property.getOwner() != null) ? property.getOwner().getUsername() : "None";
                
                model.addRow(new Object[] {
                    property.getPropertyId(),
                    property.getBlockNumber(), 
                    property.getPropertyNumber(),   
                    property.getStatus(),
                    ownerName,
                    property.getContactPrice(),
                    property.getPropertySize(),
                    property.getFloors(),
                    type
                });
            }
        }
    }
    
    private void loadBookingsToTable() {
        DefaultTableModel requestModel = (DefaultTableModel) requestTable.getModel();
        requestModel.setRowCount(0); // Clear existing rows

        for(Booking bookingRequest : propertyManager.getBookingForAgent(agent)) {
            
            Property property = bookingRequest.getProperty();
            String type;
            if (property instanceof TownHouse) {
                type = "Town House";
            } else if (property instanceof SemiDetached) {
                type = "Semi-Detached";
            } else if (property instanceof Detached) {
                type = "Detached";
            } else {
                type = "";
            }

            requestModel.addRow(new Object[] {
                property.getPropertyId(),
                property.getBlockNumber(), 
                property.getPropertyNumber(),   
                property.getStatus(),
                bookingRequest.getCustomer().getUsername(),
                property.getContactPrice(),
                property.getPropertySize(),
                property.getFloors(),
                type
            });
        }
    }

    
    private void setupTable() {
        propertyTable.setRowSelectionAllowed(true);
        propertyTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        propertyTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = propertyTable.getSelectedRow();

                if (row >= 0) { 
                    int propertyId = (int) propertyTable.getValueAt(row, 0); // first column = propertyId
                    selectedProperty = agent.getProperty(propertyId);
                } else {
                    selectedProperty = null;
                }
            }
        });
    }
    
    private void setupRequestTable() {
        requestTable.setRowSelectionAllowed(true);
        requestTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        requestTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = requestTable.getSelectedRow();

                if (row >= 0) {
                    int propertyId = (int) requestTable.getValueAt(row, 0);
                    String customerName = (String) requestTable.getValueAt(row, 4);

                    // Find the actual Booking object
                    for (Booking booking : propertyManager.getBookingForAgent(agent)) {
                        if (booking.getProperty().getPropertyId() == propertyId &&
                            booking.getCustomer().getUsername().equals(customerName)) {
                            selectedBooking = booking;
                            break;
                        }
                    }
                } else {
                    selectedBooking = null;
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavigatorPanel;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel PropertiesPanel;
    private javax.swing.JPanel RequestPanel;
    private javax.swing.JButton confirmBookingButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton propertiesButton;
    private javax.swing.JTable propertyTable;
    private javax.swing.JButton removeBookingButton;
    private javax.swing.JButton removeReservationButton;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton requestsButton;
    // End of variables declaration//GEN-END:variables
}