/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyApp;

import MyLib.Block;
import MyLib.Customer;
import MyLib.Detached;
import MyLib.Property;
import MyLib.PropertyManager;
import MyLib.SemiDetached;
import MyLib.Session;
import MyLib.TownHouse;
import MyLib.UserManager;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * 
 */
public class CustomerDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CustomerDashboard.class.getName());
    private UserManager userManager;
    private PropertyManager propertyManager;
    private Customer customer;
    private Property selectedProperty = null;
    private int selectedBlock = 0;
    
    /**
     * Creates new form AdminDashboard
     */
    public CustomerDashboard(UserManager userManager, PropertyManager propertyManager, Customer customer) {
        this.userManager = userManager;
        this.propertyManager = propertyManager;
        this.customer = customer;
        initComponents();
        setLocationRelativeTo(null);
        setupTable();
        loadPropertiesToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NavigatorPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        ownedPropertiesPanelButton = new javax.swing.JButton();
        propertiesPanelButton = new javax.swing.JButton();
        Parent = new javax.swing.JPanel();
        PropertiesPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertyTable = new javax.swing.JTable();
        bookButton = new javax.swing.JButton();
        blockSelector = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        minSizeField = new javax.swing.JTextField();
        maxSizeField = new javax.swing.JTextField();
        minPriceField = new javax.swing.JTextField();
        maxPriceField = new javax.swing.JTextField();
        filterButton = new javax.swing.JButton();
        OwnedPropertiesPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ownedPropertiesTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavigatorPanel.setLayout(null);

        logoutButton.setText("Logout");
        logoutButton.addActionListener(this::logoutButtonActionPerformed);
        NavigatorPanel.add(logoutButton);
        logoutButton.setBounds(30, 680, 170, 60);

        ownedPropertiesPanelButton.setText("Owned Properties");
        ownedPropertiesPanelButton.addActionListener(this::ownedPropertiesPanelButtonActionPerformed);
        NavigatorPanel.add(ownedPropertiesPanelButton);
        ownedPropertiesPanelButton.setBounds(40, 110, 150, 50);

        propertiesPanelButton.setText("Properties");
        propertiesPanelButton.addActionListener(this::propertiesPanelButtonActionPerformed);
        NavigatorPanel.add(propertiesPanelButton);
        propertiesPanelButton.setBounds(40, 30, 150, 50);

        Parent.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Properties");

        propertyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Property ID", "Block Number", "Property Number", "Status", "Owner", "Property Price", "Property Size", "Property Floors", "Property Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(propertyTable);

        bookButton.setText("Book Property");
        bookButton.addActionListener(this::bookButtonActionPerformed);

        blockSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "1", "2", "3", "4", "5" }));
        blockSelector.addActionListener(this::blockSelectorActionPerformed);

        jLabel3.setText("Block Number: ");

        jLabel4.setText("Size:");

        jLabel5.setText("Price: ");

        filterButton.setText("Filter");
        filterButton.addActionListener(this::filterButtonActionPerformed);

        javax.swing.GroupLayout PropertiesPanelLayout = new javax.swing.GroupLayout(PropertiesPanel);
        PropertiesPanel.setLayout(PropertiesPanelLayout);
        PropertiesPanelLayout.setHorizontalGroup(
            PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookButton))
                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(blockSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                                .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(minPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(maxPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(minSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(maxSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(37, 37, 37)
                                .addComponent(filterButton)))))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        PropertiesPanelLayout.setVerticalGroup(
            PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(blockSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PropertiesPanelLayout.createSequentialGroup()
                                .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(minSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PropertiesPanelLayout.createSequentialGroup()
                                .addComponent(filterButton)
                                .addGap(2, 2, 2)))
                        .addGroup(PropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(minPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PropertiesPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(bookButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Parent.add(PropertiesPanel, "PropertiesPanel");

        jLabel1.setText("Owned Properties");

        ownedPropertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Property ID", "Block Number", "Property Number", "Status", "Property Price", "Property Size", "Property Floors", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ownedPropertiesTable);

        jButton1.setText("Confirm Purchase");

        javax.swing.GroupLayout OwnedPropertiesPanelLayout = new javax.swing.GroupLayout(OwnedPropertiesPanel);
        OwnedPropertiesPanel.setLayout(OwnedPropertiesPanelLayout);
        OwnedPropertiesPanelLayout.setHorizontalGroup(
            OwnedPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnedPropertiesPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(OwnedPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(OwnedPropertiesPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        OwnedPropertiesPanelLayout.setVerticalGroup(
            OwnedPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OwnedPropertiesPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(OwnedPropertiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OwnedPropertiesPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OwnedPropertiesPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Parent.add(OwnedPropertiesPanel, "OwnedPropertiesPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavigatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavigatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Session.logout();
        
        new Authentication(userManager, propertyManager).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ownedPropertiesPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownedPropertiesPanelButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(Parent.getLayout());
        cl.show(Parent, "OwnedPropertiesPanel");
    }//GEN-LAST:event_ownedPropertiesPanelButtonActionPerformed

    private void propertiesPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertiesPanelButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(Parent.getLayout());
        cl.show(Parent, "PropertiesPanel");
    }//GEN-LAST:event_propertiesPanelButtonActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookButtonActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        // TODO add your handling code here:
        filterProperties();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void blockSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockSelectorActionPerformed
        // TODO add your handling code here:
        String selected = (String) blockSelector.getSelectedItem();
        
        if(selected == null || selected.equals("All")) {
            selectedBlock = 0;
        }
        else {
            selectedBlock = Integer.parseInt(selected);
        }
    }//GEN-LAST:event_blockSelectorActionPerformed

    private void loadPropertiesToTable() {
        DefaultTableModel model = (DefaultTableModel) propertyTable.getModel();
        model.setRowCount(0); // Clear existing rows
        
        Integer blockFilter;
        if(selectedBlock == 0) {
            blockFilter = null;
        }
        else {
            blockFilter = selectedBlock;
        }
        
        Double minPrice = parseDoubleOrNull(minPriceField.getText());
        Double maxPrice = parseDoubleOrNull(maxPriceField.getText());
        Double minSize = parseDoubleOrNull(minSizeField.getText());
        Double maxSize = parseDoubleOrNull(maxSizeField.getText());
        
        for (Block block : customer.getAllBlocks()) {
            if (blockFilter != null) {
                if (block.getBlockNumber() != blockFilter) {
                    continue;
                }
            }

            for (Property property : block.getProperties()) {
                if (minPrice != null) {
                    if (property.getContactPrice() < minPrice) {
                        continue;
                    }
                }

                if (maxPrice != null) {
                    if (property.getContactPrice() > maxPrice) {
                        continue;
                    }
                }

                if (minSize != null) {
                    if (property.getPropertySize() < minSize) {
                        continue;
                    }
                }

                if (maxSize != null) {
                    if (property.getPropertySize() > maxSize) {
                        continue;
                    }
                }

                String type;
                if (property instanceof TownHouse) {
                    type = "Town House";
                } else if (property instanceof SemiDetached) {
                    type = "Semi-Detached";
                } else if (property instanceof Detached) {
                    type = "Detached";
                } else {
                    type = "";
                }

                model.addRow(new Object[]{
                    property.getPropertyId(),
                    block.getBlockNumber(),
                    property.getPropertyNum(),
                    property.getStatus(),
                    property.getOwner(),
                    property.getContactPrice(),
                    property.getPropertySize(),
                    property.getFloors(),
                    type
                });
            }
        }
    }
    
    private Double parseDoubleOrNull(String text){
        if (text == null || text.isEmpty())
            return null;
        if (!text.matches("\\d+(\\.\\d+)?"))
            return null;
        return Double.parseDouble(text);
    }
    
    private boolean isInvalidPrice(String text, Double price) {
        return text != null && !text.isEmpty() && price == null;
    }
    
    private void filterProperties(){
        double minPrice = parseDoubleOrNull(minPriceField.getText());
        double maxPrice = parseDoubleOrNull(maxPriceField.getText());
        
        // If minimum price is invalid
        if (isInvalidPrice(minPriceField.getText(), minPrice)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid numeric value for minimum price.");
            return;
        }

        // Check if the maximum price is invalid
        if (isInvalidPrice(maxPriceField.getText(), maxPrice)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid numeric value for maximum price.");
            return;
        }
        
        loadPropertiesToTable();
    }
        
    private void loadOwnedPropertiesToTable() { // not loaded/used yet
        DefaultTableModel ownedModel = (DefaultTableModel) ownedPropertiesTable.getModel();
        
        ownedModel.setRowCount(0); // Clear existing rows
        
        for(Block block : customer.getAllBlocks()) { // Gets all block(s) in ArrayList<Block> blocks
            for(Property property : block.getProperties()) { // Gets all properties in ArrayList<Property> properties for each block
                String type = "";
            
                if(property instanceof TownHouse) {
                    type = "Town House";
                }
                else if(property instanceof SemiDetached) {
                    type = "Semi-Detached";
                }
                else if(property instanceof Detached) {
                    type = "Detached";
                }
                
                if(property.getOwner().equals(customer)) { // ?If owner attribute in property is customer, then add to row
                    ownedModel.addRow(new Object[] {
                        property.getPropertyId(),
                        block.getBlockNumber(),
                        property.getPropertyNum(),
                        property.getStatus(),
                        property.getOwner(),
                        property.getContactPrice(),
                        property.getPropertySize(),
                        property.getFloors(),
                        type
                    });
                }
            }
        }
    }
    
    private void setupTable() {
        propertyTable.setRowSelectionAllowed(true);
        propertyTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        
        propertyTable.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int row = propertyTable.getSelectedRow();

                if (row >= 0) { // a row is selected
                    int propertyId = (int) propertyTable.getValueAt(row, 0); // first column = propertyId
                    selectedProperty = customer.getProperty(propertyId);
                } else {
                    selectedProperty = null;
                }
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavigatorPanel;
    private javax.swing.JPanel OwnedPropertiesPanel;
    private javax.swing.JPanel Parent;
    private javax.swing.JPanel PropertiesPanel;
    private javax.swing.JComboBox<String> blockSelector;
    private javax.swing.JButton bookButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTextField maxPriceField;
    private javax.swing.JTextField maxSizeField;
    private javax.swing.JTextField minPriceField;
    private javax.swing.JTextField minSizeField;
    private javax.swing.JButton ownedPropertiesPanelButton;
    private javax.swing.JTable ownedPropertiesTable;
    private javax.swing.JButton propertiesPanelButton;
    private javax.swing.JTable propertyTable;
    // End of variables declaration//GEN-END:variables
}
